### ISSUE TITLE
Catching mouse events

### ISSUE THREAD

**Issue by jendelel** [sanshu/protaeljs#8]
Hi, 

first of all, congratulations on such a great tool. 

I was wondering, it is possible to catch mouse events? More specifically, I would like to set a callback function for mouse hovering and clicking (so that I know what residue that mouse is hovering above, and the same for features if possible). You must already handle in the zoom thank to the zoom feature. It there a public 
API as well?

Something like:
```
protael.onMouseHoverCallback(function (residueIndex) {
   console.log(residueIndex);
});
```

To give an example, I need something like [this](http://prank.projekty.ms.mff.cuni.cz:8080/analyze/upload/4x09) - the website currently uses pViz, but I think protaeljs is better.

Thank you very much, 
Lukas

**Comment by sanshu** [comment]
Hi Lukas, 

As of now, you can use following for mouseOver:

```
protael.onMouseOver(function (e) {
   console.log(protael.toOriginalX(protael.mouseToSvgXY(e).x));
});﻿
```

Mayya

**Comment by jendelel** [comment]
Hi Mayya, 

it works great. Thank you! 

If it wasn't too much trouble, would it be possible to somehow find out whether the mouse is hovering a feature and what the feature is, so that I could for example highlight the feature and more details about it somewhere else on the website? Moreover, the ability to handle a mouse click on a feature would be fantastic. If it was too much work, then it probably isn't worth it. 

Thank you again, 

Lukas
